#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f 0/cellToRegion*
rm -rf 0/channel
rm -rf 0/chamber
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/channel/polyMesh
rm -rf constant/chamber/polyMesh
rm -rf VTK

